### ISSUE TITLE
Registration page: Due Week 4 Completion  (module 6.1)

### ISSUE THREAD

**Issue by jimmyleast** [ryan-kite/Provisio#3]
-  Students can pick the number of fields, but at minimum, there should be fields for email address, first name, last name, and password. 

-  Additional comments:  
    ●	All customers should be assigned a unique customerId. This will be used in the loyalty points page. 
    ●	All customers should use their email address as the “username” field and the password should be at least 8 characters in length and include one uppercase and one lowercase letter (hint: use regular expression). 
    ●	Passwords should be hashed and/or encrypted using standard security practices (use the Internet for ideas/code snippets; be sure to cite all external authors).

**Comment by dhunsanj** [comment]
I have completed the registration page. Thank you for the cooperation.

**Comment by jimmyleast** [comment]
complete front end and backend code fist pass
