### ISSUE TITLE
SQL populate: Raise standard room rates 5% and holiday reservation rates by and additional 5%

### ISSUE THREAD

**Issue by jimmyleast** [ryan-kite/Provisio#32]
Since more and more people are traveling, the room rates have gone up by 5%. Additionally, if the customer makes reservation for a holiday stay (Fourth of July, Christmas Eve, New Years Eve) the increased rate is another 5%.

**Comment by jimmyleast** [comment]
Update current costs by 5%
write if statement for reservation date

**Comment by ryan-kite** [comment]
This was a pain in the A$$ :)
