### ISSUE TITLE
Reservation look up page: Due Week 6 completion (module 9.1)

### ISSUE THREAD

**Issue by jimmyleast** [ryan-kite/Provisio#8]
●	Note: Provide customers with a page to look up a previous reservation. The page should include a field to search by reservation ID and display a summary of the reservation. List the location, room size, number of guests, amenities, and check-in/check-out dates.

**Comment by ryan-kite** [comment]
Prototype for this page has been completed

**Comment by jimmyleast** [comment]
This has been handled in the summary page

**Comment by jimmyleast** [comment]
finished in the summary page
